### PR TITLE
Reports and Tella Web documentation

### PR DESCRIPTION
**Pull request by carohadad**

### CODE REVIEW

**Comment by raphmim** [comment]
@carohadad did you push it to https://beta.docs.tella-app.org? I cannot see it there.

**Comment by carohadad** [comment]
No, not yet ❤️

**Comment by carohadad** [comment]
@raphmim here it is the deployed version on beta https://beta.docs.tella-app.org/

**Review by juandans01 — APPROVED** [review]

**Comment by juandans01** [comment]
looks good to me, also the doc site is looking amazing!

**Review by ahlem-jarrar — APPROVED** [review]

**Pull request merged**
